"""add tenders checkpoints and bids

Revision ID: fcede08e06a2
Revises: 57706ba9b8d4
Create Date: 2026-09-14 22:43:24.387745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcede08e06a2'
down_revision: Union[str, Sequence[str], None] = '57706ba9b8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('procurement_type', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'UNDER_REVIEW', name='tender_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('checkpoint_set_frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tenders_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenders'))
    )
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('quotation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_PRELIMINARY_REVIEW', 'REVIEWED', name='bid_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bids_organization_id_organizations')),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('fk_bids_tender_id_tenders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids'))
    )
    op.create_index(op.f('ix_bids_organization_id'), 'bids', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bids_tender_id'), 'bids', ['tender_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_requirement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('requirement_class', sa.Enum('MANDATORY', 'CONDITIONAL', 'INFORMATIONAL', name='requirement_class'), nullable=False),
    sa.Column('validation_method', sa.Enum('DOCUMENT_PRESENCE', 'NUMERIC_THRESHOLD', 'DATE_VALIDITY', 'EXPERIENCE_THRESHOLD', 'PROJECT_COUNT', 'TECHNICAL_NUMERIC', 'SEMANTIC', 'DECLARATION_PRESENCE', 'ENTITY_CONSISTENCY', 'MANUAL_REVIEW', name='validation_method'), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('threshold_unit', sa.String(length=50), nullable=True),
    sa.Column('expected_evidence_type', sa.String(length=100), nullable=True),
    sa.Column('applicability_definition', sa.Text(), nullable=True),
    sa.Column('validity_definition', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(length=150), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_checkpoints_confirmed_by_users')),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('fk_checkpoints_tender_id_tenders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkpoints'))
    )
    op.create_index(op.f('ix_checkpoints_tender_id'), 'checkpoints', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkpoints_tender_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_bids_tender_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_organization_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_table('tenders')
    # ### end Alembic commands ###
